stages:
    - build
    - test

build:
    stage: build
    script:
    - pip install -r requirements.txt
    - python3 setup.py install
    - pip install -U pytest

test:
    stage: test
    script:
    - python3 -m pytest ./tests
