stages:
    - build
    - test

build:
    stage: build
    script:
    - pip install -r requirements.txt
    - pip install -U pytest

test:
    stage: test
    script:
    - find ./tests -name test_*.py -exec python3 -m pytest $file \;
