name: CI/CD Pi

on:
  push:
    branches: [master, RnD]
  pull_request:
    branches: [master, RnD]

jobs:
  validation:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
        mpi: [openmpi]
  
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install pytest
        make setup
        make install

    - name: Test with pytest
      run: |
        make test

    - name: Set up MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}

    - name: Set up parallel code
      run: make install
      working-directory: ./parallel

    - name: Test parallel with pytest
      run: make test_parallel
      working-directory: ./parallel

  nightly:
    name: Build nightly distribution
    if: github.event_name == 'push' && github.ref == 'refs/heads/RnD'
    needs: validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: 'true'
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install 
          build
          --user
      - name: Build wheel and tarball
        run: python3 -m build
      - name: Store dist as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-nightly-package-dist
          path: dist/




