name: main

on:
  push:
    branches: [master, RnD, mpi_workflow]
  pull_request:
    branches: [master. RnD]

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        mpi: [mpich, openmpi]
        include:
        - os: ubuntu-latest
          mpi: mpich
          install-mpi: sudo apt install -y mpich libmpich-dev
        - os: ubuntu-latest
          mpi: openmpi
          install-mpi: sudo apt install -y openmpi-bin libopenmpi-dev
        - os: macos-latest
          mpi: mpich
          install-mpi: brew install mpich
        - os: macos-latest
          mpi: openmpi
          install-mpi: brew install openmpi

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up MPI
      run: ${{ matrix.install-mpi }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest
        pip install mpi4py
    - name: Test with pytest
      run: |
        pytest tests
