name: CD Pipeline

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-release:
    name: Build the release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: 'true'
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install 
          build
          --user
      - name: Build wheel and tarball
        run: python3 -m build
      - name: Store dist as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-release-package-dist
          path: dist/

  publish-to-pypi:
    name: Publish dist to PyPi
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ssequence
    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v5
        with:
          name: python-release-package-dist
          path: dist/
      - name: Publish dist to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-test-pypi:
    name: Publish dist to TestPyPi
    needs:
      - build-release
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/ssequence

    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v5
        with:
          name: python-release-package-dist
          path: dist/
      - name: Publish dist to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
